version: "3.7"
services:
  db:
    image: mysql:5.7.33
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=pythonlogin
      - MYSQL_ROOT_PASSWORD=abc123

  app:
    build: app
    restart: always

  web:
    build: web
    restart: always
    ports:
      - 80:80
